version: "2"
run:
  timeout: 5m
  allow-parallel-runners: true
  go: "1.23"

linters:
  enable:
    - copyloopvar
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - unused
  disable:
    # These linters have issues with Go 1.23 range-over-function patterns
    - staticcheck
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "Cannot range over.*func\\(yield func"
      - linters:
          - staticcheck  
        text: "internal error.*unhandled type.*ir\\.ArrayConst"
