version: 2

project_name: litellm-operator

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: manager
    main: ./cmd/main.go
    binary: manager
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.buildType=nightly
    flags:
      - -trimpath
    ignore:
      - goos: windows
      - goos: darwin

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:nightly-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:nightly-{{ .ShortCommit }}-amd64"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.description=Nightly build"
    extra_files:
      - go.mod
      - go.sum
      - api/
      - internal/
      - cmd/
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:nightly-arm64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:nightly-{{ .ShortCommit }}-arm64"
    dockerfile: Dockerfile
    goos: linux
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.description=Nightly build"
    extra_files:
      - go.mod
      - go.sum
      - api/
      - internal/
      - cmd/

docker_manifests:
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:nightly"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:nightly-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:nightly-arm64"
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:nightly-{{ .ShortCommit }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:nightly-{{ .ShortCommit }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:nightly-{{ .ShortCommit }}-arm64"

# Minimal archives for nightly builds
archives:
  - format: binary
    name_template: "{{ .ProjectName }}_nightly_{{ .Os }}_{{ .Arch }}"

# Disable checksums for nightly builds
checksum:
  disable: true

# Simplified changelog for nightly builds
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .ProjectName }}"
  prerelease: true
  draft: false
  name_template: "Nightly Build {{ .Date }}"
  header: |
    ## 🌙 Nightly Build - {{ .Date }}
    
    **⚠️ This is an automated nightly build for testing purposes.**
    
    This build contains the latest changes from the main branch as of {{ .Date }}.
    It should **NOT** be used in production environments.
    
    ### Container Images
    
    - `ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:nightly`
    - `ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:nightly-{{ .ShortCommit }}`
    
    ### Changes since last nightly build:
  footer: |
    ---
    📅 **Build Date**: {{ .Date }}  
    🏷️ **Commit**: {{ .FullCommit }}  
    🔄 **Automated**: This release was created automatically by the nightly build workflow.
    
    For stable releases, please see the [releases page](https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}/releases?q=tag%3Av).

# Sign container images for nightly builds
# signs:
#   - cmd: cosign
#     env:
#       - COSIGN_EXPERIMENTAL=1
#     certificate: '${artifact}.pem'
#     args:
#       - sign-blob
#       - --oidc-issuer=https://token.actions.githubusercontent.com
#       - --output-certificate=${certificate}
#       - --output-signature=${signature}
#       - ${artifact}
#       - --yes
#     artifacts: checksum 