//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionRef) DeepCopyInto(out *ConnectionRef) {
	*out = *in
	out.SecretRef = in.SecretRef
	out.InstanceRef = in.InstanceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionRef.
func (in *ConnectionRef) DeepCopy() *ConnectionRef {
	if in == nil {
		return nil
	}
	out := new(ConnectionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSecretKeys) DeepCopyInto(out *DatabaseSecretKeys) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSecretKeys.
func (in *DatabaseSecretKeys) DeepCopy() *DatabaseSecretKeys {
	if in == nil {
		return nil
	}
	out := new(DatabaseSecretKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSecretRef) DeepCopyInto(out *DatabaseSecretRef) {
	*out = *in
	out.Keys = in.Keys
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSecretRef.
func (in *DatabaseSecretRef) DeepCopy() *DatabaseSecretRef {
	if in == nil {
		return nil
	}
	out := new(DatabaseSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Gateway) DeepCopyInto(out *Gateway) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Gateway.
func (in *Gateway) DeepCopy() *Gateway {
	if in == nil {
		return nil
	}
	out := new(Gateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ingress) DeepCopyInto(out *Ingress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ingress.
func (in *Ingress) DeepCopy() *Ingress {
	if in == nil {
		return nil
	}
	out := new(Ingress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitModelInstance) DeepCopyInto(out *InitModelInstance) {
	*out = *in
	out.ModelCredentials = in.ModelCredentials
	in.LiteLLMParams.DeepCopyInto(&out.LiteLLMParams)
	in.AdditionalProperties.DeepCopyInto(&out.AdditionalProperties)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitModelInstance.
func (in *InitModelInstance) DeepCopy() *InitModelInstance {
	if in == nil {
		return nil
	}
	out := new(InitModelInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceRef) DeepCopyInto(out *InstanceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceRef.
func (in *InstanceRef) DeepCopy() *InstanceRef {
	if in == nil {
		return nil
	}
	out := new(InstanceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMInstance) DeepCopyInto(out *LiteLLMInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMInstance.
func (in *LiteLLMInstance) DeepCopy() *LiteLLMInstance {
	if in == nil {
		return nil
	}
	out := new(LiteLLMInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMInstanceList) DeepCopyInto(out *LiteLLMInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiteLLMInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMInstanceList.
func (in *LiteLLMInstanceList) DeepCopy() *LiteLLMInstanceList {
	if in == nil {
		return nil
	}
	out := new(LiteLLMInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMInstanceSpec) DeepCopyInto(out *LiteLLMInstanceSpec) {
	*out = *in
	out.DatabaseSecretRef = in.DatabaseSecretRef
	out.RedisSecretRef = in.RedisSecretRef
	out.Ingress = in.Ingress
	out.Gateway = in.Gateway
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]InitModelInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMInstanceSpec.
func (in *LiteLLMInstanceSpec) DeepCopy() *LiteLLMInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(LiteLLMInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMInstanceStatus) DeepCopyInto(out *LiteLLMInstanceStatus) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMInstanceStatus.
func (in *LiteLLMInstanceStatus) DeepCopy() *LiteLLMInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(LiteLLMInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMParams) DeepCopyInto(out *LiteLLMParams) {
	*out = *in
	if in.InputCostPerToken != nil {
		in, out := &in.InputCostPerToken, &out.InputCostPerToken
		*out = new(string)
		**out = **in
	}
	if in.OutputCostPerToken != nil {
		in, out := &in.OutputCostPerToken, &out.OutputCostPerToken
		*out = new(string)
		**out = **in
	}
	if in.InputCostPerSecond != nil {
		in, out := &in.InputCostPerSecond, &out.InputCostPerSecond
		*out = new(string)
		**out = **in
	}
	if in.OutputCostPerSecond != nil {
		in, out := &in.OutputCostPerSecond, &out.OutputCostPerSecond
		*out = new(string)
		**out = **in
	}
	if in.InputCostPerPixel != nil {
		in, out := &in.InputCostPerPixel, &out.InputCostPerPixel
		*out = new(string)
		**out = **in
	}
	if in.OutputCostPerPixel != nil {
		in, out := &in.OutputCostPerPixel, &out.OutputCostPerPixel
		*out = new(string)
		**out = **in
	}
	if in.ApiKey != nil {
		in, out := &in.ApiKey, &out.ApiKey
		*out = new(string)
		**out = **in
	}
	if in.ApiBase != nil {
		in, out := &in.ApiBase, &out.ApiBase
		*out = new(string)
		**out = **in
	}
	if in.ApiVersion != nil {
		in, out := &in.ApiVersion, &out.ApiVersion
		*out = new(string)
		**out = **in
	}
	if in.VertexProject != nil {
		in, out := &in.VertexProject, &out.VertexProject
		*out = new(string)
		**out = **in
	}
	if in.VertexLocation != nil {
		in, out := &in.VertexLocation, &out.VertexLocation
		*out = new(string)
		**out = **in
	}
	if in.VertexCredentials != nil {
		in, out := &in.VertexCredentials, &out.VertexCredentials
		*out = new(string)
		**out = **in
	}
	if in.RegionName != nil {
		in, out := &in.RegionName, &out.RegionName
		*out = new(string)
		**out = **in
	}
	if in.AwsAccessKeyID != nil {
		in, out := &in.AwsAccessKeyID, &out.AwsAccessKeyID
		*out = new(string)
		**out = **in
	}
	if in.AwsSecretAccessKey != nil {
		in, out := &in.AwsSecretAccessKey, &out.AwsSecretAccessKey
		*out = new(string)
		**out = **in
	}
	if in.AwsRegionName != nil {
		in, out := &in.AwsRegionName, &out.AwsRegionName
		*out = new(string)
		**out = **in
	}
	if in.WatsonXRegionName != nil {
		in, out := &in.WatsonXRegionName, &out.WatsonXRegionName
		*out = new(string)
		**out = **in
	}
	if in.CustomLLMProvider != nil {
		in, out := &in.CustomLLMProvider, &out.CustomLLMProvider
		*out = new(string)
		**out = **in
	}
	if in.TPM != nil {
		in, out := &in.TPM, &out.TPM
		*out = new(int)
		**out = **in
	}
	if in.RPM != nil {
		in, out := &in.RPM, &out.RPM
		*out = new(int)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int)
		**out = **in
	}
	if in.StreamTimeout != nil {
		in, out := &in.StreamTimeout, &out.StreamTimeout
		*out = new(int)
		**out = **in
	}
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(int)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.ConfigurableClientsideAuthParams != nil {
		in, out := &in.ConfigurableClientsideAuthParams, &out.ConfigurableClientsideAuthParams
		*out = new([]runtime.RawExtension)
		if **in != nil {
			in, out := *in, *out
			*out = make([]runtime.RawExtension, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.LiteLLMCredentialName != nil {
		in, out := &in.LiteLLMCredentialName, &out.LiteLLMCredentialName
		*out = new(string)
		**out = **in
	}
	if in.LiteLLMTraceID != nil {
		in, out := &in.LiteLLMTraceID, &out.LiteLLMTraceID
		*out = new(string)
		**out = **in
	}
	if in.MaxFileSizeMB != nil {
		in, out := &in.MaxFileSizeMB, &out.MaxFileSizeMB
		*out = new(int)
		**out = **in
	}
	if in.MaxBudget != nil {
		in, out := &in.MaxBudget, &out.MaxBudget
		*out = new(string)
		**out = **in
	}
	if in.BudgetDuration != nil {
		in, out := &in.BudgetDuration, &out.BudgetDuration
		*out = new(string)
		**out = **in
	}
	if in.UseInPassThrough != nil {
		in, out := &in.UseInPassThrough, &out.UseInPassThrough
		*out = new(bool)
		**out = **in
	}
	if in.UseLiteLLMProxy != nil {
		in, out := &in.UseLiteLLMProxy, &out.UseLiteLLMProxy
		*out = new(bool)
		**out = **in
	}
	if in.MergeReasoningContentInChoices != nil {
		in, out := &in.MergeReasoningContentInChoices, &out.MergeReasoningContentInChoices
		*out = new(bool)
		**out = **in
	}
	if in.ModelInfo != nil {
		in, out := &in.ModelInfo, &out.ModelInfo
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.MockResponse != nil {
		in, out := &in.MockResponse, &out.MockResponse
		*out = new(string)
		**out = **in
	}
	if in.AutoRouterConfigPath != nil {
		in, out := &in.AutoRouterConfigPath, &out.AutoRouterConfigPath
		*out = new(string)
		**out = **in
	}
	if in.AutoRouterConfig != nil {
		in, out := &in.AutoRouterConfig, &out.AutoRouterConfig
		*out = new(string)
		**out = **in
	}
	if in.AutoRouterDefaultModel != nil {
		in, out := &in.AutoRouterDefaultModel, &out.AutoRouterDefaultModel
		*out = new(string)
		**out = **in
	}
	if in.AutoRouterEmbeddingModel != nil {
		in, out := &in.AutoRouterEmbeddingModel, &out.AutoRouterEmbeddingModel
		*out = new(string)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.AdditionalProps != nil {
		in, out := &in.AdditionalProps, &out.AdditionalProps
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMParams.
func (in *LiteLLMParams) DeepCopy() *LiteLLMParams {
	if in == nil {
		return nil
	}
	out := new(LiteLLMParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Model) DeepCopyInto(out *Model) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Model.
func (in *Model) DeepCopy() *Model {
	if in == nil {
		return nil
	}
	out := new(Model)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Model) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCredentialSecretKeys) DeepCopyInto(out *ModelCredentialSecretKeys) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCredentialSecretKeys.
func (in *ModelCredentialSecretKeys) DeepCopy() *ModelCredentialSecretKeys {
	if in == nil {
		return nil
	}
	out := new(ModelCredentialSecretKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCredentialSecretRef) DeepCopyInto(out *ModelCredentialSecretRef) {
	*out = *in
	out.Keys = in.Keys
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCredentialSecretRef.
func (in *ModelCredentialSecretRef) DeepCopy() *ModelCredentialSecretRef {
	if in == nil {
		return nil
	}
	out := new(ModelCredentialSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelInfo) DeepCopyInto(out *ModelInfo) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.DBModel != nil {
		in, out := &in.DBModel, &out.DBModel
		*out = new(bool)
		**out = **in
	}
	if in.TeamID != nil {
		in, out := &in.TeamID, &out.TeamID
		*out = new(string)
		**out = **in
	}
	if in.TeamPublicModelName != nil {
		in, out := &in.TeamPublicModelName, &out.TeamPublicModelName
		*out = new(string)
		**out = **in
	}
	if in.AdditionalProps != nil {
		in, out := &in.AdditionalProps, &out.AdditionalProps
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelInfo.
func (in *ModelInfo) DeepCopy() *ModelInfo {
	if in == nil {
		return nil
	}
	out := new(ModelInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelList) DeepCopyInto(out *ModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Model, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelList.
func (in *ModelList) DeepCopy() *ModelList {
	if in == nil {
		return nil
	}
	out := new(ModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSpec) DeepCopyInto(out *ModelSpec) {
	*out = *in
	out.ConnectionRef = in.ConnectionRef
	in.LiteLLMParams.DeepCopyInto(&out.LiteLLMParams)
	in.ModelInfo.DeepCopyInto(&out.ModelInfo)
	out.ModelSecretRef = in.ModelSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSpec.
func (in *ModelSpec) DeepCopy() *ModelSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelStatus) DeepCopyInto(out *ModelStatus) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ModelName != nil {
		in, out := &in.ModelName, &out.ModelName
		*out = new(string)
		**out = **in
	}
	if in.LiteLLMParams != nil {
		in, out := &in.LiteLLMParams, &out.LiteLLMParams
		*out = new(LiteLLMParams)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelId != nil {
		in, out := &in.ModelId, &out.ModelId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelStatus.
func (in *ModelStatus) DeepCopy() *ModelStatus {
	if in == nil {
		return nil
	}
	out := new(ModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NilKeys) DeepCopyInto(out *NilKeys) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NilKeys.
func (in *NilKeys) DeepCopy() *NilKeys {
	if in == nil {
		return nil
	}
	out := new(NilKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisSecretKeys) DeepCopyInto(out *RedisSecretKeys) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisSecretKeys.
func (in *RedisSecretKeys) DeepCopy() *RedisSecretKeys {
	if in == nil {
		return nil
	}
	out := new(RedisSecretKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisSecretRef) DeepCopyInto(out *RedisSecretRef) {
	*out = *in
	out.Keys = in.Keys
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisSecretRef.
func (in *RedisSecretRef) DeepCopy() *RedisSecretRef {
	if in == nil {
		return nil
	}
	out := new(RedisSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}
