//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSecretKeys) DeepCopyInto(out *DatabaseSecretKeys) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSecretKeys.
func (in *DatabaseSecretKeys) DeepCopy() *DatabaseSecretKeys {
	if in == nil {
		return nil
	}
	out := new(DatabaseSecretKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSecretRef) DeepCopyInto(out *DatabaseSecretRef) {
	*out = *in
	out.Keys = in.Keys
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSecretRef.
func (in *DatabaseSecretRef) DeepCopy() *DatabaseSecretRef {
	if in == nil {
		return nil
	}
	out := new(DatabaseSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Gateway) DeepCopyInto(out *Gateway) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Gateway.
func (in *Gateway) DeepCopy() *Gateway {
	if in == nil {
		return nil
	}
	out := new(Gateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ingress) DeepCopyInto(out *Ingress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ingress.
func (in *Ingress) DeepCopy() *Ingress {
	if in == nil {
		return nil
	}
	out := new(Ingress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMInstance) DeepCopyInto(out *LiteLLMInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMInstance.
func (in *LiteLLMInstance) DeepCopy() *LiteLLMInstance {
	if in == nil {
		return nil
	}
	out := new(LiteLLMInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMInstanceList) DeepCopyInto(out *LiteLLMInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiteLLMInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMInstanceList.
func (in *LiteLLMInstanceList) DeepCopy() *LiteLLMInstanceList {
	if in == nil {
		return nil
	}
	out := new(LiteLLMInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiteLLMInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMInstanceSpec) DeepCopyInto(out *LiteLLMInstanceSpec) {
	*out = *in
	out.DatabaseSecretRef = in.DatabaseSecretRef
	out.RedisSecretRef = in.RedisSecretRef
	out.Ingress = in.Ingress
	out.Gateway = in.Gateway
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMInstanceSpec.
func (in *LiteLLMInstanceSpec) DeepCopy() *LiteLLMInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(LiteLLMInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteLLMInstanceStatus) DeepCopyInto(out *LiteLLMInstanceStatus) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteLLMInstanceStatus.
func (in *LiteLLMInstanceStatus) DeepCopy() *LiteLLMInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(LiteLLMInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisSecretKeys) DeepCopyInto(out *RedisSecretKeys) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisSecretKeys.
func (in *RedisSecretKeys) DeepCopy() *RedisSecretKeys {
	if in == nil {
		return nil
	}
	out := new(RedisSecretKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisSecretRef) DeepCopyInto(out *RedisSecretRef) {
	*out = *in
	out.Keys = in.Keys
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisSecretRef.
func (in *RedisSecretRef) DeepCopy() *RedisSecretRef {
	if in == nil {
		return nil
	}
	out := new(RedisSecretRef)
	in.DeepCopyInto(out)
	return out
}
